# TASK_5

scraping data about hockey teams: you have to scrap the first page table's data (Team name, year, wins, losses, win%, goals for(gf), golaagainst(ga) from this website: https://www.scrapethissite.com/pages/forms/?page_num=1

In [1]:
import requests
from bs4 import BeautifulSoup
import csv

In [2]:
url = "https://www.scrapethissite.com/pages/forms/?page_num=1"

In [3]:
response = requests.get(url)

In [4]:
soup = BeautifulSoup(response.text, 'html.parser')

In [5]:
table = soup.find('table')

In [6]:
headers = [th.text.strip() for th in table.find('tr').find_all('th')]

In [7]:
rows = []
for row in table.find_all('tr')[1:]:
    rows.append([td.text.strip() for td in row.find_all('td')])

In [8]:
with open('hockey_teams.csv', mode='w', newline='', encoding='utf-8') as file:
    writer = csv.writer(file)
    writer.writerow(headers)
    writer.writerows(rows)

In [9]:
import pandas as pd

df = pd.read_csv("hockey_teams.csv", encoding="utf-8")
df

,Team Name,Year,Wins,Losses,OT Losses,Win %,Goals For (GF),Goals Against (GA),+ / -
0,Boston Bruins,1990,44,24,NaN,0.550,299,264,35
1,Buffalo Sabres,1990,31,30,NaN,0.388,292,278,14
2,Calgary Flames,1990,46,26,NaN,0.575,344,263,81
3,Chicago Blackhawks,1990,49,23,NaN,0.613,284,211,73
4,Detroit Red Wings,1990,34,38,NaN,0.425,273,298,-25
5,Edmonton Oilers,1990,37,37,NaN,0.463,272,272,0
6,Hartford Whalers,1990,31,38,NaN,0.388,238,276,-38
7,Los Angeles Kings,1990,46,24,NaN,0.575,340,254,86
8,Minnesota North Stars,1990,27,39,NaN,0.338,256,266,-10
9,Montreal Canadiens,1990,39,30,NaN,0.487,273,249,24
10,New Jersey Devils,1990,32,33,NaN,0.400,272,264,8
11,New York Islanders,1990,25,45,NaN,0.312,223,290,-67
12,New York Rangers,1990,36,31,NaN,0.450,297,265,32
13,Philadelphia Flyers,1990,33,37,NaN,0.412,252,267,-15
14,Pittsburgh Penguins,1990,41,33,NaN,0.512,342,305,37
15,Quebec Nordiques,1990,16,50,NaN,0.200,236,354,-118
16,St. Louis Blues,1990,47,22,NaN,0.588,310,250,60
17,Toronto Maple Leafs,1990,23,46,NaN,0.287,241,318,-77
18,Vancouver Canucks,1990,28,43,NaN,0.350,243,315,-72
19,Washington Capitals,1990,37,36,NaN,0.463,258,258,0
20,Winnipeg Jets,1990,26,43,NaN,0.325,260,288,-28
21,Boston Bruins,1991,36,32,NaN,0.450,270,275,-5
22,Buffalo Sabres,1991,31,37,NaN,0.388,289,299,-10
23,Calgary Flames,1991,31,37,NaN,0.388,296,305,-9
24,Chicago Blackhawks,1991,36,29,NaN,0.450,257,236,21